<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SoundArcade.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" />
    <PackageReference Include="System.Speech" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
  </ItemGroup>

</Project>
